docker/start.sh

ensure secrets from swarm are available for use

add secrets for prod runtime

---

Dockerfile
docker/start.sh

remove rails / panoptes code and clean up deps and cmds to start lita.

Update dockerfile start script

---

handlers/deployment.rb

add talk jenkins jobs for chat ops

add talk deployment jobs

---

handlers/deployment.rb

remove old unused jobs and add comments about the state of chat ops deployment code.

cleanup the chat ops deployment code

---

.travis.yml

test against ruby 2.6 to stay current

test ruby 2.6

---

lita_config.rb

this is no longer valid as it was removed in #61

remove factoid handler

---

.travis.yml
Dockerfile
README.md
docker-compose.yml
handlers/deployment.rb
handlers/lintott.rb
lita_env.rb
spec/spec_helper.rb

Setup testing env

---

handlers/deployment.rb

Allow more repo lookups if they conform to the expected deploy setup (avoid keying every repo that uses json / file etc) and add better error messages so folks know what to fix

genericize lookup deployed status with error messages

---

handlers/deployment.rb

report missing services on url, status resources on url and the status data itself

add error handling

---

handlers/deployment.rb

use the '+' concat operator that handles the frozen string, https://ruby-doc.org/core-2.3.0/String.html#method-i-2B-40

avoid mutating a frozen string

---

Jenkinsfile
kubernetes/redis.yaml

And add dry runs in Jenkinsfile

Fix affinity indentation

---

handlers/deployment.rb

And clean up old Panoptes commands.

Add DB migration command

---

handlers/deployment.rb

increase the timeout to 90s and allow config via env var

increase jenkins job timeout

---

handlers/deployment.rb

these are all for the old jenkins deploy jobs, removing the dead code

remove unused deployment handler code

---

handlers/deployment.rb

remove the commented out testing setup

---

handlers/deployment.rb
lib/github_status_reporter.rb

track the latest commit id of default branch (HEAD) on GH when deploying the repo
this should align to the deployed commit via the jenkins job (update release tag) for repos we deploy via lita

add deploy commit tracking & `lita history $REPO` cmd

---

handlers/deployment.rb

linked to the work in https://github.com/zooniverse/front-end-monorepo/pull/3432
this PR adds a lita deployment fem branch deployment cmd, `lita fem branch deploy $branch-name`

add fem branch deploy cmd

---

handlers/deployment.rb

follow up on #141 - this PR updates the help text of the `fem branch deploy` cmd

update help text to match the actual cmd

---

Dockerfile
Gemfile
Gemfile.lock

Bandaid fix in order to get lita deploys to work and while team figures out next steps for chatops. 
Gem lita-slack using forked repo

install git in order to fetch forked bandaid repo

---

Gemfile
Gemfile.lock

have lita-slack pull from zooniverse fork vs developer fork

have lita-slack pull from zooniverse fork vs developer fork

---

handlers/security_reporter.rb

social should have reports but the rest have been archived

update ignored repos

---

Gemfile
Gemfile.lock
README.md
handlers/deployment.rb
lita_config.rb

switched to gh actions so we don't need this service dependency anymore

remove jenkins dependency from lita

---

handlers/deployment.rb

Rename `deploy.yml` to `deploy_production.yml`.

Update the subject set search command
