- Gemfile
- README.md
- lita_config.rb
possible solution for the gem requires when working in dev / production mode. turns out lita defaults to a shell without a config.
> add gem groups for dev / production

- lita-zooniverse/lib/lita-zooniverse.rb
- lita-zooniverse/lib/lita/api/ouroboros_project.rb
- lita-zooniverse/lib/lita/api/panoptes_project.rb
- lita-zooniverse/lib/lita/api/project.rb
- lita-zooniverse/lib/lita/handlers/deployment.rb
- lita-zooniverse/lib/lita/handlers/projects.rb
- lita_config.rb
- lita_env.rb
closes #4, allow the user to decide which projects are migrated by showing the legacy id's. 
Also allow dev env not to need jenkins env vars and refactored to static contexts for search and then string representation to instance methods.
> report legacy zooniverse id for migrated legacy projects

- handlers/deployment.rb
docker hub production tag will now auto build a new production ami via jenkins web hook that reflects on the incoming tag name (production). 
no need to run update tag, wait and check docker hub and then build. this should all happen naturally now.
> update panoptes update tag job

- Dockerfile
seems the openssl libs are missing bits that event machine uses to correctly build for newer TLS versions, using libssl-dev installed the same underlying library but when a rebuilt event machine now connects securely. Ideally this is taken care of by the underlying ruby build vs a manual dev package install. 
Moving to a new ruby build may be the best way to fix the problem, if so remove / revert this dependency addition.
> add libssl-dev to ensure event machine works

- handlers/deployment.rb
Merge only when Caesar is in the cluster and is using the `production-release` tag for production deployment.
> Remove Caesar short-circuit for k8s migration

- Dockerfile
bump ruby version to 2.6
we're currently testing on ruby 2.4 only but we're running on 2.3 via docker
> use the tested ruby version

- Gemfile
- Gemfile.lock
removing this as we don't use the functionality, i'll leave the data in redis namespace `handlers:bucket` in case we want to restore this functionality at some stage. 
Also this is a security vector as this is a git repo and not a published gem (slightly easier to get commit rights to the repo vs a gem).
> remove martens bucket lita handlers

- handlers/deployment.rb
- spec/spec_helper.rb
1. Allow docker to be used for testing / developing handlers for lita app. 
2. Also use docker compose testing via travis for consistency between our environments
3. Add a generalised deployed status cmd to lita (similar to `lita deploy $REPO` e.g. `lita status zooniverse/zoo-stats-api-graphql`)
This PR needs to be rebased over #62 once that is in.
> generalize status command for k8s apps

- .gitignore
- lita_config.rb
- load_handlers.rb
- spec/load_handlers_spec.rb
add test coverage to ensure we test the lita handler file loading on boot. 
Linked to #76 as that forgot to remove the handler from `lita_config.rb` and broke the app
> Add loading lita handler spec

- handlers/deployment.rb
removing these old deployment jobs as they are now handled by the talk repo jenkinsfile and k8s deployment jobs, e.g. `lita deploy talk-api`
> remove old talk deployment jobs

- docker-compose.yml
- handlers/deployment.rb
- kubernetes/deployment.tmpl
- lib/github_status_reporter.rb
add `lita status all` cmd to see the state of all known deployed repositories, E.g.
```
Lita > lita status all
talk-api
HEAD : is the currently deployed version.
PRODUCTION : is the currently deployed version.
panoptes
HEAD : 1 undeployed commit. https://github.com/zooniverse/panoptes/compare/zooniverse:a2f30d5...zooniverse:d66aaeb
PRODUCTION-RELEASE : is the currently deployed version.
```
This tracks the deployed repo names in a sorted redis set and reports each of these repo statuses in order from most frequently to least deployed. 
It will remove from the tracking set any repos that cannot be reported via GH (missing commit info, typos in name etc).
> Add lita status all cmd

- handlers/deployment.rb
when deploying via slack, ensure we don't have any repo names like 'panoptes  '  as these don't align to any known repo and thus break the `status all` check.
> remove any surrounding whitespace in repo names

- lib/github_status_reporter.rb
allow https://github.com/zooniverse/redsea to have it's deployment status reported. 
using new GH `main` branch and deployed from `main` to prod (no staging env yet)
> add redsea deploy status

- lib/github_status_reporter.rb
Alias `zooniverse/pandora` to translations.zooniverse.org.
> Add a status URL for translations

- lib/github_status_reporter.rb
Add www.zooniverse.org/commit_id.txt as the deploy status URL for PFE.
> Add a status URL for PFE

- lib/github_status_reporter.rb
Fixes theia not reporting status.
The whole current paradigm is using text files or json responses, we don't want to have to parse a HTML page to get the status out of it (if it's in there)
instead of silently failing this will raise an relevant error instead.
> raise if we get a html response

- lib/github_status_reporter.rb
Add https://lab.zooniverse.org/commit_id.txt as the status URL for the lab.
https://github.com/zooniverse/pfe-lab/pull/252 adds the commit ID to the lab deployment actions.
> Add pfe-lab status check

- lib/github_status_reporter.rb
Add fe-project.zooniverse.org/commit_id.txt as the status URL for the monorepo.
> Add front-end-monorepo status check

- kubernetes/deployment.tmpl
lita is sometimes dying through OOM
OOMKilled Details	
Pod	OOMKills	Restarts	Namespace	Image
lita-c4bff4747-5d725 	3 	636 	default 	docker.io/zooniverse/lita:9e6b9c3d5302f0615855583be28d9a439b3d62bc
> increase cpu and ram limits

- handlers/deployment.rb
allow chat ops cmd to rebuild the subject-set-search API dataset to ensure new EC data is available for the project tools.
> add rebuild subject-set-search API job

- lib/github_status_reporter.rb
NextJS project app URLs are now prefixed with `/projects`.
> Fix monorepo status URL

- lib/zooniverse_github.rb
Talk uses `production-release` tag to deploy via jenkins so we need to use this tag for lita to trigger deploys https://github.com/zooniverse/talk-api/blob/0799a540c2fd62f5e3b49341c6a4c70790e1b441/Jenkinsfile#L48
> use production-release tag for talk api deploys

- handlers/deployment.rb
- lib/zooniverse_github.rb
update a repo's `production-migrate` tag directly via the gh client vs running the job through jenkins's `Update production-migrate tag` job
> switch migrate jobs to use gh client for production-migrate tag

- handlers/security_reporter.rb
- lib/zooniverse_github.rb
**CURRENT CHANGES**
- Update Query to have graphql filter for correct state which is OPEN (this will give us a true number of issues as seen on repo's security tab and saves us the need to filter)
- removing cellect from repos to skip since it is still in use
-  display along with totals amount of high and critical issues and how many unique packages cause these alerts.
- update format of reporter to display `[repo](link to repo) -- alerts`
**TODO (for another PR/hackday)**
- report by repo (I think personally it is better to use specific graphql query done by repo i.e.
- REFACTOR  https://github.com/zooniverse/lita/pull/120#discussion_r825932135 I do like Cam's review on refactoring, adding this as debt for me to do later 
- Sentry error reporting (Will open in another PR)
``` 
def …
```
> Security reporter improvements

- lita_config.rb
updating slack config for lita to display mrkdown. following docs:  https://github.com/litaio/lita-slack. unsure if this will work since the options for .parse wasn't really clear, but followed https://api.slack.com/reference/surfaces/formatting#parsing_modes as a guide.
> update to parse to mkdwn

- lib/zooniverse_github.rb
switch from the non-authed `lita status $repo` compare request to the authed client one. This will avoid rate limits such as 
> GET https://api.github.com/repos/zooniverse/interventions-gateway/compare/6efdd0b29756d400d40cf0016f733c269dde3f52...HEAD: 403 - API rate limit exceeded for 40.88.52.209. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
Full backtrace:
/usr/local/bundle/gems/octokit-4.19.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
> use the authed client to avoid rate limits

- lib/zooniverse_github.rb
This PR allows the status cmd to ignore case when matching repo names and makes life easier for the folks using chat ops. We can do this as github repo names are case insensitive so shouldn't clash on any chat ops cmds.
Before this PR something like
```
Lita > lita status panoptes-front-end
Failed to fetch the deployed commit for this repo.
No service is running on the url - https://panoptes-front-end.zooniverse.org
```
After this PR change we now get
```
Lita > lita status panoptes-front-end
HEAD : is the currently deployed version.
PRODUCTION-RELEASE : is the currently deployed version.
```
> case insensitive repo url name matching

- handlers/security_reporter.rb
- lib/zooniverse_github.rb
filters out for new alerts of the week (returns only the alerts created 7 days before the `lita security report new this week` command gets called.)
> Security new this week

- handlers/deployment.rb
- lib/zooniverse_github.rb
This will allow us to run Github Actions via Lita in Slack. Adds `lita action REPO FILENAME BRANCH` and some shortcuts for `lita static nginx` and `lita static ingress` (see https://github.com/zooniverse/static/pull/277). I've got to do some more testing because it doesn't seem like it's respecting the branch as an input parameter, all my tests have run on master so far. Need to dig into the API endpoint (https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event) and ensure that I'm sending it what it wants.
Feedback welcome.
> Apply ingresses via chatops

- Gemfile
- Gemfile.lock
- lib/zooniverse_github.rb
this PR adds the sugar repo for chat ops deploys. It also fixes the existing URLs to ensure they can use the root page json fallback options as well, i.e. avoid adding the `commit_id.txt` suffix as it's added dynamically when attempting to fetch status via https://github.com/zooniverse/lita/blob/ccc431ea84391fdfd43ed13fe4403b11c36dd4a9/lib/zooniverse_github.rb#L271
> Add sugar repo to irregular URL

- lib/zooniverse_github.rb
Updates lita's list of irregular urls to include Anti-Slavery Manuscripts urls, so in Slack #deploys `lita status anti-slavery-manuscripts` works, similar to Scribes of the Cairo Geniza.
> Add anti-slavery-manuscripts to irregular urls list

- lib/zooniverse_github.rb
Updates lita's list of irregular urls to include Notes from Nature Field Book url, so in Slack `lita status notes-from-nature-field-book` works as expected.
> Add notes-from-nature-field-book to irregular urls list

- handlers/deployment.rb
https://github.com/zooniverse/subject-set-search-api/pull/23 changes the name of `deploy.yml`, so this will need to merge once that merges.
> Update subject set search API command

- Gemfile
- Gemfile.lock
update lita slack  with logging version on random websocket close and http_router with master version to get rid of noise unescape obsolete warnings
> update lita-slack  and pin http_router to master version 

- lib/zooniverse_github.rb
Post-switcheroo, www.zooniverse.org/commit_id.txt is served from the fe-root app, not PFE. This confuses lita, who uses that URL for PFE checks. This updates that check to use the `static.zooniverse.org/www.zooniverse.org` path which still gets updated on PFE deploys but isn't served by www. 
Also updated FEM's check to check the fe-root app instead of projects. Using the app directly instead of www to avoid the CDN, just in case.
> Update PFE and FEM's commit check URLs

- lib/zooniverse_github.rb
Aggregation was migrated to the standard deployment scheme, utilizing the `production-release` tag and dual actions and templates. This removes the repo from the list of non-standard "deployed from master" apps.
> Remove aggregation from nonstandard tag list

- handlers/security_reporter.rb
Adding more repos to the list of skipped security alerts. These repos are not archived (yet), but the frontend team does not dedicate time to managing security alerts for them.
Note - I saw that Exercise is archived so I don't think it needs to be included, but please feel free to edit this PR as needed!
> Add repos to skip list in security reporter
